name: yassine_project
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  firebase_core: ^3.4.0
  firebase_auth: ^5.2.0
  cloud_firestore: ^5.4.0
  firebase_messaging: ^15.1.0
  provider: ^6.1.5+1
  intl: ^0.20.2
  flutter_local_notifications: ^18.0.1
  google_maps_flutter: ^2.6.1
  geocoding: ^4.0.0
  geolocator: ^12.0.0
  flutter_native_splash: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/images/

flutter_native_splash:
  color: "#121212"        # Dark background
  image: assets/logo.png  # Your logo file
  android: true
  ios: true
  web: false
  android_12:
    image: assets/logo.png
    icon_background_color: "#121212"